// Generated by CoffeeScript 1.9.2
(function() {
  $(document).ready(function() {
    var c, generateMap, map;
    c = $("#canvas")[0].getContext("2d");
    map = void 0;
    generateMap = function() {
      this.CANVAS_SIZE = parseInt($("#canvas").attr("width"));
      this.MAP_SIZE = parseInt($("#mapSize").val());
      switch ($("#algorythm").val()) {
        case "BSP":
          bsp.config.ITERATIONS = parseInt($("#bspIterations").val());
          if ($("#deletingEnabled").prop("checked")) {
            bsp.config.ROOM_DELETING_RATIO = parseFloat($("#deletingRatio").val());
          } else {
            bsp.config.ROOM_DELETING_RATIO = 0;
          }
          if ($("#doorsEnabled").prop("checked")) {
            bsp.config.DOOR_CHANCE = parseInt($("#doorChance").val());
          } else {
            bsp.config.DOOR_CHANCE = 0;
          }
          bsp.config.DRAW_WALLS = $("#drawWalls").prop("checked");
          map = bsp.generate(MAP_SIZE);
          return map.paint(c);
      }
    };
    $("#mapSize").val(MAP_SIZE);
    if (window.SHOW_GRID) {
      $("#showGrid").prop("checked", "on");
    } else {
      $("#showGrid").removeProp("checked", "on");
    }
    if (window.SHOW_WALLS) {
      $("#showWalls").prop("checked", "on");
    } else {
      $("#showWalls").removeProp("checked", "on");
    }
    if (window.SHOW_DOORS) {
      $("#showDoors").prop("checked", "on");
    } else {
      $("#showDoors").removeProp("checked", "on");
    }
    $("#bspIterations").val(bsp.config.ITERATIONS);
    $("#deletingRatio").val(bsp.config.ROOM_DELETING_RATIO);
    if (bsp.config.ROOM_DELETING_RATIO > 0) {
      $("#deletingEnabled").prop("checked", "on");
    } else {
      $("#ratioRestEnabled").removeProp("checked", "on");
    }
    $("#doorChance").val(bsp.config.DOOR_CHANCE);
    if (bsp.config.DOOR_CHANCE > 0) {
      $("#doorsEnabled").prop("checked", "on");
    } else {
      $("#doorsEnabled").removeProp("checked", "on");
    }
    if (bsp.config.DRAW_WALLS) {
      $("#drawWalls").prop("checked", "on");
    } else {
      $("#drawWalls").removeProp("checked", "on");
    }
    $("#deletingEnabled").change(function() {
      if ($("#deletingEnabled").prop("checked")) {
        return $("#deletingRatio").removeAttr("disabled", "");
      } else {
        return $("#deletingRatio").attr("disabled", "");
      }
    });
    $("#doorsEnabled").change(function() {
      if ($("#doorsEnabled").prop("checked")) {
        return $("#doorChance").removeAttr("disabled", "");
      } else {
        return $("#doorChance").attr("disabled", "");
      }
    });
    $("#generate").click(generateMap);
    $("#showGrid").change(function() {
      window.SHOW_GRID = $("#showGrid").prop("checked");
      return map.paint(c);
    });
    $("#showWalls").change(function() {
      window.SHOW_WALLS = $("#showWalls").prop("checked");
      return map.paint(c);
    });
    $("#showDoors").change(function() {
      window.SHOW_DOORS = $("#showDoors").prop("checked");
      return map.paint(c);
    });
    $('[data-togle="tooltip"]').tooltip();
    return generateMap();
  });

}).call(this);

//# sourceMappingURL=controller.js.map
